# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/logging/writers/sqlite/sqlite.bif (plugin mode).

export {



module LogSQLite;






} # end of export section
module GLOBAL;
